package entities;

/**
 * Books category
 */
public enum BookCategory
{
    ARCHITECTURE, ART, BIOGRAPHY_AND_MEMOIR, BUSINESS,CHILDRENS_FICTION,COOKING_FOOD_WINE, FAMILY_AND_PARENTING,
    FICTION, FUN_AND_GAMES, GARDENING, HEALTH, HISTORY, HOME_REFERENCE, MEDICAL, MUSIC,NONFICTION, PERFORMING_ARTS, PETS,
    PHILOSOPHY, PHOTOGRAPHY,RELIGION, SOCIAL_SCIENCE, SPORTS, TRAVEL
}
